name: dmri_seg

channels:
    - conda-forge
    - pnlbwh
    
dependencies:
    - python=3.9
    - cudatoolkit=11.8
    - cudnn==8.6
    - nibabel>=2.2.1
    - ants
    - pip
    - pip:
        - tensorflow
        - ipython
        - prompt-toolkit==2.0.1
        - gputil
        - scikit-image==0.16.2
        - git+https://github.com/pnlbwh/conversion.git
